package com.rohit.chitchat

object MyConstants {


    val NODE_PURCHASES: String = "purchases"
    val CURRENT_SUBSCRIPTION: String = "currentSubscription"
    val BASE_64_KEY: String? = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg9Sl3NbeRwdYBAjHZdwStWTG2I25NjQz13lVb4BbUcOh6yv0zuTKVcfx4CkxKMZaVrveVHcV75srZv8uVNxq7aGz62tWgFN6ogca2c0QU2W/ckxD7XowuYCLEnm9azqUZUo9En3NTwszzwInSbrLniOOldh7dSqtpp/IBgWFoAOlwI9V9RK8Avy6Z9DfIX5tDUvaEqgmnNb7tMz0F04tLUNX9CVFkLhJ/ttqZxTABubsSqoLWmJ6h46T6cTEJS/mgdZkjx6Svi2HGP1PlLvxKXdjEhMLMs2sbdPS9PohvJlErIkC0RZjYTfl/r8yUe33Bqt1Q/vGNNt1H1B2meWU3wIDAQAB"
    val PUR_99_10 = "10_pur"
    val PUR_199_20 = "20_pur"
    val PUR_299_30 = "30_pur"
    val PUR_399_40 = "40_pur"
    val PUR_499_50 = "50_pur"
    val SEARCH_DISTANCE: String = "searchDistance"
    val NODE_LIKED_USERS: String = "likedUsers"
    val USER_GENDER: String = "userGender"
    val TOKEN: String = "myToken"
    val COUNTRY_CODE: String? = "countryCode"
    val CHAT_LIST_SCREEN: String? = "chatListScreen"
    val FROM: String? = "fromScreen"
    val DELETE_TIME: String? = "deleteTime"
    val OTHER_USER_TOKEN: String = "token"
    val GHOST_MODE: String = "ghostMode"
    val ON: String? = "on"
    val OFF: String? = "off"
    val USER_CAPTIONS: String = "userCaptions"

    var PHONE_NUMBER = "phoneNumber"
    var NODE_USERS = "Users"
    var NODE_CHATS = "Chats"
    var NOTI_REQUEST_TYPE = "request"
    var NODE_CHAT_FIRENDS = "ChatFriends"
    var NODE_ONLINE_STATUS = "onlineStatus"
    var NODE_NAME = "Name"
    var NODE_IMAGE = "image"
    var NODE_MOBILE = "Mobile"
    var IS_LOGIN = "isLogin"
    var USER_NAME = "userName"
    var USER_IMAGE = "userImage"
    var USER_PHONE = "userPhone"
    var USER_LATITUDE = "userLat"
    var USER_LONGITUDE = "userLong"
    var OTHER_USER_NAME = "otherUserName"
    var OTHER_USER_IMAGE = "otherUserImage"
    var LIKE_STATUS = "likeStatus"
    var OTHER_USER_PHONE = "otherUserPhone"
    var SEEN_STATUS = "seenStatus"
    var FIREBASE_BASE_URL = "https://chitforchat-d1ee5-default-rtdb.asia-southeast1.firebasedatabase.app/"


}